apiVersion: v1
kind: ConfigMap
metadata:
  name: credential
data:
  DATABASE_URL: postgres://postgres:postgres@db:5432/registry
  IDENTITY_BASE_URL: http://identity:3332
  SCHEMA_BASE_URL: http://credential-schema:3333
  CREDENTIAL_SERVICE_BASE_URL: https://example.com/credentials
  JWKS_URI: ""
  ENABLE_AUTH: "false"
  QR_TYPE: url
