apiVersion: v1
kind: Service
metadata:
  name: credential
spec:
  selector:
    app: credential
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credential
spec:
  selector:
    matchLabels:
      app: credential
  template:
    metadata:
      labels:
        app: credential
    spec:
      containers:
      - name: credential
        image: ghcr.io/sunbird-rc/sunbird-rc-credentials-service:v2.0.0
        envFrom:
          - configMapRef:
              name: credential
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:3000/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:3000/health
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000
