apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
  - port: 9002
    targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:23.4.2.11-alpine
        readinessProbe:
          exec:
            command:
              - wget
              - --no-verbose
              - --tries=1
              - --spider
              - http://localhost:8123/ping
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 9000
