apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
  - port: 8081
    targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: ghcr.io/sunbird-rc/sunbird-rc-core:v2.0.0
        envFrom:
          - configMapRef:
              name: registry
          - secretRef:
              name: registry
        readinessProbe:
          exec:
            command:
              - wget
              - -nv
              - -t1
              - --spider
              - http://localhost:8081/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - wget
              - -nv
              - -t1
              - --spider
              - http://localhost:8081/health
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
