apiVersion: v1
kind: Secret
metadata:
  name: registry
type: Opaque
stringData:
  KEYCLOAK_SECRET: 3SP6NcM49JPXbyVJLRZQU8CPRlsAiTTL1I+NkkWxCRA=
  ELASTIC_SEARCH_PASSWORD: examplePass
  sunbird_keycloak_user_password: abcd@123
  filestorage_secret_key: "12345678"
  sunbird_sso_admin_client_secret: 3SP6NcM49JPXbyVJLRZQU8CPRlsAiTTL1I+NkkWxCRA=
