apiVersion: v1
kind: Service
metadata:
  name: notification-ms
spec:
  selector:
    app: notification-ms
  ports:
  - port: 8765
    targetPort: 8765

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ms
spec:
  selector:
    matchLabels:
      app: notification-ms
  template:
    metadata:
      labels:
        app: notification-ms
    spec:
      containers:
      - name: notification-ms
        image: ghcr.io/sunbird-rc/sunbird-rc-notification-service:v2.0.0
        env:
          - name: TRACK_NOTIFICATIONS
            value: "false"
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kafka-service:9092
        readinessProbe:
          exec:
            command:
              - wget
              - -nv
              - -t1
              - --spider
              - http://localhost:8765/notification-service/v1/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - wget
              - -nv
              - -t1
              - --spider
              - http://localhost:8765/notification-service/v1/health
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8765
