apiVersion: v1
kind: Service
metadata:
  name: claim-ms
spec:
  selector:
    app: claim-ms
  ports:
  - port: 8082
    targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim-ms
spec:
  selector:
    matchLabels:
      app: claim-ms
  template:
    metadata:
      labels:
        app: claim-ms
    spec:
      containers:
      - name: claim-ms
        image: ghcr.io/sunbird-rc/sunbird-rc-claim-ms:v2.0.0
        env:
          - name: connectionInfo_uri
            value: jdbc:postgresql://db:5432/registry
          - name: connectionInfo_username
            value: postgres
          - name: connectionInfo_password
            value: postgres
          - name: sunbirdrc_url
            value: http://registry:8081
        readinessProbe:
          exec:
            command:
              - wget
              - -nv
              - -t1
              - --spider
              - http://localhost:8082/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - wget
              - -nv
              - -t1
              - --spider
              - http://localhost:8082/health
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
