apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:6.2.0
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: '2181'
          - name: ZOOKEEPER_TICK_TIME
            value: '2000'
          - name: ZOOKEEPER_SERVER_ID
            value: "1"
        readinessProbe:
          exec:
            command:
              - echo
              - ruok
              - "|"
              - nc
              - localhost
              - "2181"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - echo
              - ruok
              - "|"
              - nc
              - localhost
              - "2181"
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        ports:
        - containerPort: 2181
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"

