apiVersion: v1
kind: Service
metadata:
  name: file-storage
spec:
  selector:
    app: file-storage
  ports:
  - port: 9000
    targetPort: 9000
    name: p1
  - port: 9001
    targetPort: 9001
    name: p2
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: file-storage
spec:
  selector:
    matchLabels:
      app: file-storage
  serviceName: file-storage
  replicas: 1
  template:
    metadata:
      labels:
        app: file-storage
    spec:
      containers:
      - name: file-storage
        image: quay.io/minio/minio
        env:
          - name: MINIO_ROOT_USER
            value: admin
          - name: MINIO_ROOT_PASSWORD
            value: "12345678"
        volumeMounts:
          - name: file-storage-vol
            mountPath: /data
        args:
          - server
          - --address
          - 0.0.0.0:9000
          - --console-address
          - 0.0.0.0:9001
          - /data
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:9000/minio/health/live
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:9000/minio/health/live
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 9000
        - containerPort: 9001

  volumeClaimTemplates:
  - metadata:
      name: file-storage-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
