apiVersion: v1
kind: Service
metadata:
  name: encryption-service
spec:
  selector:
    app: encryption-service
  ports:
  - port: 8013
    targetPort: 8013

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encryption-service
spec:
  selector:
    matchLabels:
      app: encryption-service
  template:
    metadata:
      labels:
        app: encryption-service
    spec:
      containers:
      - name: encryption-service
        image: ghcr.io/sunbird-rc/encryption-service:v2.0.0
        envFrom:
          - configMapRef:
              name: encryption-service
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:8013/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:8013/health
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8013
