apiVersion: v1
kind: Service
metadata:
  name: context-proxy-service
spec:
  selector:
    app: context-proxy-service
  ports:
  - port: 4400
    targetPort: 4400

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-proxy-service
spec:
  selector:
    matchLabels:
      app: context-proxy-service
  template:
    metadata:
      labels:
        app: context-proxy-service
    spec:
      containers:
      - name: context-proxy-service
        image:  ghcr.io/sunbird-rc/sunbird-rc-context-proxy-service
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - localhost:4400/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - curl
              - -f
              - localhost:4400/health
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 4400
