apiVersion: v1
kind: Service
metadata:
  name: digilocker-certificate-api
spec:
  selector:
    app: digilocker-certificate-api
  ports:
  - port: 8087
    targetPort: 8087

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digilocker-certificate-api
spec:
  selector:
    matchLabels:
      app: digilocker-certificate-api
  template:
    metadata:
      labels:
        app: digilocker-certificate-api
    spec:
      containers:
      - name: digilocker-certificate-api
        image: ghcr.io/sunbird-rc/sunbird-rc-digilocker-certificate-api
        env:
          - name: KEYCLOAK_CLIENT_ID
            value: admin-api
          - name: KEYCLOAK_CLIENT_SECRET
            value: 3SP6NcM49JPXbyVJLRZQU8CPRlsAiTTL1I+NkkWxCRA=
          - name: DIGILOCKER_HMAC_AUTHKEY
            value: generated_hmac_key_placeholder
          - name: DIGILOCKER_AUTH_KEYNAME
            value: x-digilocker-hmac
          - name: PORT
            value: "8087"
        volumeMounts:
          - name: digilocker-certificate-api-vol
            mountPath: /go/config/
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8087

      volumes:
        - name: digilocker-certificate-api-vol
          persistentVolumeClaim:
            claimName: digilocker-certificate-api-pvc
