apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digilocker-certificate-api-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
