apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    app.kubernetes.io/name: myingress
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port: 
              number: 80
      - pathType: Prefix
        path: "/proxy"
        backend:
          service:
            name: context-proxy-service
            port: 
              number: 4400
      - pathType: Prefix
        path: "/auth"
        backend:
          service:
            name: keycloak
            port: 
              number: 8080
      - pathType: Prefix
        path: "/public-key-service"
        backend:
          service:
            name: public-key-service
            port: 
              number: 3300
