apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress-trimmed
  labels:
    app.kubernetes.io/name: myingress-trimmed
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/registry/(.*)"
        backend:
          service:
            name: registry
            port: 
              number: 8081
      - pathType: ImplementationSpecific
        path: "/bucket/(.*)"
        backend:
          service:
            name: file-storage
            port: 
              number: 9000
      - pathType: ImplementationSpecific
        path: "/claim-ms/(.*)"
        backend:
          service:
            name: claim-ms
            port: 
              number: 8082
