apiVersion: v1
kind: Service
metadata:
  name: identity
spec:
  selector:
    app: identity
  ports:
  - port: 3332
    targetPort: 3332

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: ghcr.io/sunbird-rc/sunbird-rc-identity-service:v2.0.0
        envFrom:
          - configMapRef:
              name: identity
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:3332/health
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3332
