apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"
