apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1000

      initContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /var/lib/kafka/data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: kafka
          mountPath: /var/lib/kafka/data

      containers:
        - name: kafka
          image: confluentinc/cp-kafka:6.2.0
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka
          volumeMounts:
            - name: kafka
              mountPath: /var/lib/kafka/data
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 120

  volumeClaimTemplates:
  - metadata:
      name: kafka
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
