apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:6.2.0
        ports:
          - containerPort: 9092
        envFrom:
        - configMapRef:
            name: kafka
        readinessProbe:
          tcpSocket:
            port: 9092
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
