apiVersion: v1
kind: Secret
metadata:
  name: es-secret
stringData:
  ELASTIC_PASSWORD: 3SP6NcM49JPXbyVJLRZQU8CPRlsAiTTL1I+NkkWxCRA=
  discovery.type: single-node
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  xpack.security.enabled: "false"
