apiVersion: v1
kind: Service
metadata:
  name: metrics
spec:
  selector:
    app: metrics
  ports:
  - port: 8070
    targetPort: 8070

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
spec:
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - name: metrics
        image: ghcr.io/sunbird-rc/sunbird-rc-metrics
        env:
          - name: CLICK_HOUSE_URL
            value: clickhouse:9000
          - name: CLICKHOUSE_DATABASE
            value: default
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kafka-service:9092
          - name: KAFKA_METRICS_TOPIC
            value: events
          - name: REDIS_URL
            value: redis:6379
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:8070/health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:8070/health
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        ports:
        - containerPort: 8070
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"

